name: Run Tests

on: [push, pull_request]

jobs:
    test:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                php: ["8.3", "8.2"]

        steps:
            - uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}

            - name: Install dependencies
              run: composer install

            - name: Run Pest tests
              run: vendor/bin/pest
